[package]
name = "chip8gui"
version = "0.1.0"
edition = "2024"

[dependencies]
chip8sys = { path = "../../chip8/chip8sys" }
minifb = "0.28"
rodio = "0.21.1"

[lib]
name = "chip8gui"
path = "src/lib.rs"

